# Generated by Django 4.0.7 on 2022-09-04 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ec_base.common.constant.db_table
import ec_base.common.models.base
import ec_base.common.utils.strings
import ec_base.common.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0003_masterfiletype_masterorderstatus_masterpaymentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('desc', models.TextField(null=True)),
                ('file', models.FileField(upload_to=ec_base.common.utils.strings.get_file_field_directory, validators=[ec_base.common.utils.validators.FileSizeValidator(200)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name=ec_base.common.constant.db_table.DBTable['FILE_MANAGEMENT'], to='master.masterfiletype')),
                ('updated_by', ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['FILE_MANAGEMENT'],
            },
        ),
    ]
