# Generated by Django 4.0.7 on 2022-09-05 05:55

import django.db.models.deletion
from django.db import migrations, models

import ec_base.common.constant.db_table
import ec_base.common.utils.strings
import ec_base.common.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (ec_base.common.constant.app_label.ModelAppLabel['MASTER'], '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('desc', models.TextField(null=True)),
                ('file', models.FileField(upload_to=ec_base.common.utils.strings.get_file_field_directory,
                                          validators=[ec_base.common.utils.validators.FileSizeValidator(200)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                           related_name=ec_base.common.constant.db_table.DBTable['FILE_MANAGEMENT'],
                                           to='master.masterfiletype')),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['FILE_MANAGEMENT'],
            },
        ),
    ]
