# Generated by Django 4.0.6 on 2022-07-29 08:41

from django.db import migrations, models
import ec_base.common.constant.db_table
import ec_base.common.models.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_leave', models.BooleanField(default=False)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['STAFF'],
            },
            managers=[
                ('objects', ec_base.common.models.managers.CustomUserManager()),
            ],
        ),
    ]
