# Generated by Django 4.0.6 on 2022-07-29 08:41

from django.db import migrations, models
import django.db.models.deletion
import ec_base.common.constant.db_table
import ec_base.common.constant.master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_alter_mastercity_name_alter_masterdiscounttype_name_and_more'),
        (ec_base.common.constant.app_label.ModelAppLabel['USER_INFO'], '0001_initial'),
        (ec_base.common.constant.app_label.ModelAppLabel['STAFF'], '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name=ec_base.common.constant.db_table.DBTable['STAFF'], to='user_info.userinfo'),
        ),
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.ForeignKey(default=ec_base.common.constant.master.MasterStaffID['EMPLOYEE'], on_delete=django.db.models.deletion.RESTRICT, related_name=ec_base.common.constant.db_table.DBTable['STAFF'], to='master.masterstafftype'),
        ),
    ]
