# Generated by Django 4.0.6 on 2022-07-31 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ec_base.common.constant.db_table
import ec_base.common.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (ec_base.common.constant.app_label.ModelAppLabel['USER_INFO'], '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name=ec_base.common.constant.db_table.DBTable['CUSTOMER'], to='user_info.userinfo')),
                ('updated_by', ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['CUSTOMER'],
            },
        ),
    ]
