# Generated by Django 4.0.6 on 2022-09-07 07:54

import django.db.models.deletion
from django.db import migrations, models

import ec_base.common.constant.db_table
import ec_base.common.constant.related_name


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0001_initial'),
        (ec_base.common.constant.app_label.ModelAppLabel['ORDER'], '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discounts',
                 models.ManyToManyField(related_name=ec_base.common.constant.related_name.RelatedName['ORDER_ITEMS'],
                                        to='discount.discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                            related_name=ec_base.common.constant.db_table.DBTable['ORDER_ITEM'],
                                            to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                              related_name=ec_base.common.constant.db_table.DBTable['ORDER_ITEM'],
                                              to='product.product')),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['ORDER_ITEM'],
            },
        ),
    ]
