# Generated by Django 4.0.7 on 2022-09-05 05:55

import django.db.models.deletion
from django.db import migrations, models

import ec_base.common.constant.db_fields
import ec_base.common.constant.db_table
import ec_base.common.constant.related_name


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterCity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_CITY"],
            },
        ),
        migrations.CreateModel(
            name="MasterCustomerType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_CUSTOMER_TYPE"],
            },
        ),
        migrations.CreateModel(
            name="MasterDiscountRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_DISCOUNT_RATE"],
            },
        ),
        migrations.CreateModel(
            name="MasterDiscountType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_DISCOUNT_TYPE"],
            },
        ),
        migrations.CreateModel(
            name="MasterFileType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_FILE_TYPE"],
            },
        ),
        migrations.CreateModel(
            name="MasterOrderStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_ORDER_STATUS"],
            },
        ),
        migrations.CreateModel(
            name="MasterPaymentStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_PAYMENT_STATUS"],
            },
        ),
        migrations.CreateModel(
            name="MasterProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_PRODUCT_CATEGORY"],
            },
        ),
        migrations.CreateModel(
            name="MasterSex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_SEX"],
            },
        ),
        migrations.CreateModel(
            name="MasterShippingStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_SHIPPING_STATUS"],
            },
        ),
        migrations.CreateModel(
            name="MasterStaffType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_STAFF_TYPE"],
            },
        ),
        migrations.CreateModel(
            name="MasterDistrict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name=ec_base.common.constant.db_table.DBTable["MASTER_DISTRICT"],
                        to="master.mastercity",
                    ),
                ),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["MASTER_DISTRICT"],
                "unique_together": {
                    (
                        ec_base.common.constant.db_fields.MasterFields["NAME"],
                        ec_base.common.constant.db_fields.MasterDistrictFields["CITY"],
                    )
                },
            },
        ),
    ]
