# Generated by Django 4.0.6 on 2022-08-06 15:02

from django.db import migrations, models
import ec_base.common.constant.db_table


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDiscountRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['MASTER_DISCOUNT_RATE'],
            },
        ),
    ]
