# Generated by Django 4.0.6 on 2022-07-23 19:31

from django.db import migrations, models
import ec_base.common.constant.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='masterdiscounttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='masterproductcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mastersex',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='masterstafftype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='masterdistrict',
            unique_together={(ec_base.common.constant.db_fields.MasterDistrictFields['NAME'], ec_base.common.constant.db_fields.MasterDistrictFields['CITY'])},
        ),
    ]
