# Generated by Django 4.0.7 on 2022-10-22 06:39

from django.db import migrations, models
import ec_base.common.constant.db_table


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFilterBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['MASTER_FILTER_BY'],
            },
        ),
    ]
