# Generated by Django 4.0.6 on 2022-08-30 07:07

from django.db import migrations, models
import ec_base.common.constant.db_table


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_masterdiscountrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['MASTER_FILE_TYPE'],
            },
        ),
        migrations.CreateModel(
            name='MasterOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['MASTER_ORDER_STATUS'],
            },
        ),
        migrations.CreateModel(
            name='MasterPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['MASTER_PAYMENT_STATUS'],
            },
        ),
        migrations.CreateModel(
            name='MasterShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['MASTER_SHIPPING_STATUS'],
            },
        ),
    ]
