# Generated by Django 4.0.7 on 2022-08-28 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ec_base.common.constant.db_fields
import ec_base.common.constant.db_table
import ec_base.common.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_masterdiscountrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('discount_rate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name=ec_base.common.constant.db_table.DBTable['DISCOUNT'], to='master.masterdiscountrate')),
                ('discount_type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name=ec_base.common.constant.db_table.DBTable['DISCOUNT'], to='master.masterdiscounttype')),
                ('updated_by', ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['DISCOUNT'],
                'unique_together': {(ec_base.common.constant.db_fields.DiscountFields['DISCOUNT_TYPE_ID'], ec_base.common.constant.db_fields.DiscountFields['DISCOUNT_RATE_ID'])},
            },
        ),
    ]
