# Generated by Django 4.0.7 on 2022-09-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ec_base.common.constant.db_table
import ec_base.common.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (ec_base.common.constant.app_label.ModelAppLabel['MASTER'], '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by',
                 ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT,
                                                             related_name='%(app_label)s_%(class)s_created_by',
                                                             to=settings.AUTH_USER_MODEL)),
                ('discount_rate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                                    related_name=ec_base.common.constant.db_table.DBTable['DISCOUNT'],
                                                    to='master.masterdiscountrate')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT,
                                                    related_name=ec_base.common.constant.db_table.DBTable['DISCOUNT'],
                                                    to='master.masterdiscounttype')),
                ('updated_by',
                 ec_base.common.models.base.CurrentUserField(null=True, on_delete=django.db.models.deletion.RESTRICT,
                                                             related_name='%(app_label)s_%(class)s_updated_by',
                                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': ec_base.common.constant.db_table.DBTable['DISCOUNT'],
            },
        ),
    ]
