# Generated by Django 4.0.7 on 2022-09-05 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ec_base.common.constant.db_table
import ec_base.common.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (ec_base.common.constant.app_label.ModelAppLabel["FILE_MANAGEMENT"], "0001_initial"),
        (ec_base.common.constant.app_label.ModelAppLabel["PRODUCT"], "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "num_stars",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "created_by",
                    ec_base.common.models.base.CurrentUserField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name=ec_base.common.constant.db_table.DBTable["RATING"],
                        to="file_management.filemanagement",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name=ec_base.common.constant.db_table.DBTable["RATING"],
                        to="product.product",
                    ),
                ),
                (
                    "updated_by",
                    ec_base.common.models.base.CurrentUserField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": ec_base.common.constant.db_table.DBTable["RATING"],
            },
        ),
    ]
