export enum RouterEnum {
  home = '/',
  homeName = 'home',
  about = '/about',
  aboutName = 'about',
  login = '/login',
  loginName = 'login',
  register = '/register',
  registerName = 'register',
  forgotPassword = '/forgot-password',
  forgotPasswordName = 'forgotPassword',
  products = '/products',
  productsName = 'products',
  categories = '/categories',
  categoriesName = 'categories',
  discounts = '/discounts',
  discountsName = 'discounts',
}
